apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: vcluster-add
  namespace: argo
spec:
  eventBusName: vcluster-add
  template:
    serviceAccountName: argocd-workflow
  dependencies:
    - name: vcluster-add
      eventSourceName: vcluster-add
      eventName: vcluster-add
  triggers:
    - template:
        name: vcluster-add
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: vcluster-add-
                labels:
                  app: vcluster-add
              spec:
                entrypoint: add-to-argocd
                serviceAccountName: argocd-workflow
                arguments:
                  parameters:
                  - name: cluster
                    value: ""
                templates:
                - name: add-to-argocd
                  inputs:
                    parameters:
                    - name: cluster
                  container:
                    image: rafaeljusto/autoenv-k8s:latest
                    command: ["/bin/sh", "-c", "/etc/argocd-scripts/add-to-argocd.sh {{inputs.parameters.cluster}}"]
                    volumeMounts:
                    - name: argocd-scripts
                      mountPath: /etc/argocd-scripts/
                    env:
                    - name: USERNAME
                      valueFrom:
                        secretKeyRef:
                          key: username
                          name: argocd-login
                    - name: PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: password
                          name: argocd-login
                  volumes:
                  - name: argocd-scripts
                    configMap:
                      name: argocd-scripts
                      defaultMode: 0777
          parameters:
            - src:
                dependencyName: vcluster-add
                dataKey: body.metadata.name
              dest: spec.arguments.parameters.0.value