---
{{- required "The cluster name is required!" .Values.clusterName }}
{{- $imageTag := (lookup "cluster.x-k8s.io/v1beta1" "cluster" "autoenvs" .Values.clusterName ).metadata.labels.imageTag }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoenv
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "rafaeljusto/autoenv:{{ $imageTag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        - name: regcred