---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-app
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          provider: vcluster
  template:
    metadata:
      name: 'autoenv-app-{{name}}'
    spec:
      source:
        repoURL: https://github.com/rafaeljusto/autoenv.git
        targetRevision: 'HEAD'
        path: helm
        helm:
          parameters:
          - name: "namespace"
            value: 'example'
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: example
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true