---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          provider: vcluster
  template:
    metadata:
      name: 'autoenv-app-{{name}}'
    spec:
      source:
        repoURL: https://github.com/rafaeljusto/autoenv.git
        targetRevision: 'HEAD' # TODO: We need somhow to set the {{head_sha}} from the initial PR generator
        path: helm
        helm:
          parameters:
          - name: "image.tag"
            value: 'latest' # TODO: We need somhow to set the {{head_short_sha_7}} from the initial PR generator
          - name: "namespace"
            value: 'example'
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: example
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true