apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: rafaeljusto
        repo: autoenv
        labels:
          - preview
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 15
  template:      
    metadata:
      name: 'autoenv-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/rafaeljusto/autoenv.git
        targetRevision: 'HEAD'
        path: helm-vcluster
        helm:
          parameters:
          - name: "cluster_name"
            value: 'autoenv-{{branch}}-{{number}}'
          - name: "imageTag"
            value: "v{{head_short_sha_7}}"
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      destination:
        name: in-cluster
        namespace: autoenvs
      ignoreDifferences:
        - jsonPointers:
            - /controlPlaneEndpoint
          kind: VCluster