---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-workflows
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/rafaeljusto/autoenv.git
    targetRevision: HEAD
    path: argocd-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true