---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{.Values.cluster_name}}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: {{.Values.chart_name}}
      repo: {{.Values.chart_repo}}
      version: {{.Values.chart_version}}
    values: |
      serviceCIDR: "{{.Values.serviceCIDR}}"
      ingress:
        enabled: true
        host: {{.Values.cluster_name}}.autoenvs.svc
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
  kubernetesVersion: "{{.Values.kubernetes_version}}"