replicaCount: 1
name: autoenv
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'vv1.0.0-38-gd5c0da0'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
