replicaCount: 1
name: autoenv
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'vv1.0.0-96-g6eb42c1'
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  portName: http
clusterName: ""
