replicaCount: 1
name: autoenv
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'v93a5a4b'
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 8080
  portName: http
