replicaCount: 1
name: autoenv
env: staging
namespace: staging
image:
  name: webserver-simple
  tag: 'vv1.0.0-68-gbb03c85'
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8418
  targetPort: 8080
  portName: http
