name: k8s release
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile.k8s

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rafaeljusto
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.k8s
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rafaeljusto/autoenv-k8s:latest