name: release
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find tag
        id: find_tag
        run: |
          echo "Tag: $(git describe --always)"
          echo "tag=$(git describe --always)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rafaeljusto
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rafaeljusto/autoenv:v${{ steps.find_tag.outputs.tag }}